### ISSUE TITLE
Fixed bug in _HTTP ( {request} ) script line 222

### ISSUE THREAD

**Issue by colleen-curtin** [proofgeist/mfm-http#1]
When calling MSGraph API to send mail with attachment the ResponseHeader returns more than one line; changed line 222 Set Variable $responseLine1 FROM:

GetValue($responseHeaders; 1 )

TO

Let ( [
	pattern = "HTTP/1.1";
	response = $responseHeaders;
	len = Length ( response );
	count = PatternCount ( response ; pattern );
	pos = Position ( response ; pattern ; 0 ; count )
] ;
   GetValue(
	Middle ( response ; pos ; len )
   ; 1 )
)

**Comment by toddgeist** [comment]
Ah nice catch :-)
