### ISSUE TITLE
Bug when HTTP POST includes a query string and body (i.e., data) (application/x-www-form-urlencoded only)

### ISSUE THREAD

**Issue by davegraham92120** [proofgeist/mfm-http#4]
The variable $queryStringList is used to create the data string for application/x-www-form-urlencoded requests. Since it is also used above in the Handle Query section, values from the query are inserted into the data variable, causing some HTTP requests to fail. I recommend renaming variables to avoid conflict.

Existing:
<img width="861" alt="image" src="https://github.com/user-attachments/assets/0de05363-c32f-45ca-a6e1-a4fc089c0559">
Recommended:
<img width="858" alt="image" src="https://github.com/user-attachments/assets/1056db07-b868-47d1-b2a9-5f6f4a8cfa1d">
[mfm-HTTP.fmp12.zip](https://github.com/user-attachments/files/17356801/mfm-HTTP.fmp12.zip)

**Comment by toddgeist** [comment]
Good catch Dave.
