### ISSUE TITLE
Insert From URL not immediately followed by Get (LastError)

### ISSUE THREAD

**Issue by bobi-no** [proofgeist/mfm-http#5]
<img width="912" alt="Screenshot 2024-10-14 at 11 19 53 AM" src="https://github.com/user-attachments/assets/4027ee91-54dd-4216-927d-b337ed3964b6">

It looks to me like the `$error` variable that gets assigned `Get (LastError)` should get its value assigned immediately after `Insert From URL` as assigning other variables in between would clear out the LastError value.

One could choose between swapping $error and $timerDuration, or relying on a let statement within the $error assignment to handle the $timerDuration value assignment if the $timerDuration's proximity to insert from URL needs to be higher than the one from Get(LastError).

**Comment by davegraham92120** [comment]
I was just about to report this. Thanks @bobi-no!
