### ISSUE TITLE
URL-encoding data values can cause issues with certain payloads (Content-Type: application/x-www-form-urlencoded only)

### ISSUE THREAD

**Issue by davegraham92120** [proofgeist/mfm-http#6]
I believe this section of code was duplicated from the Handle Query section, which is likely the cause of https://github.com/proofgeist/mfm-http/issues/4. It makes sense to URL-encode values for query params, but not for data. Encoding caused posts to fail when the client secret data element contained an ampersand (&). 
![image](https://github.com/user-attachments/assets/d70c6c85-efc0-4eae-87a8-5e6f3e032b72)

**Comment by toddgeist** [comment]
hmmm not so sure...

If you post "application/x-www-form-urlencoded" data an ampersand must be encoded since ampersands are the value separator.

> application/x-www-form-urlencoded: the keys and values are encoded in key-value tuples separated by an ampersand (&), with an equals symbol (=) between the key and the value (e.g., first-name=Frida&last-name=Kahlo). Non-alphanumeric characters in both keys and values are [percent-encoded](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding): this is the reason why this type is not suitable to use with binary data and you should use multipart/form-data for this purpose instead.

Percent Encoding is also known as Url Encoding.
For reference
https://en.wikipedia.org/wiki/Percent-encoding

**Comment by davegraham92120** [comment]
My bad… I think it was a percent symbol, not the ampersand. I’ll confirm when I’m back at my desk. Sent from my iPhoneOn Oct 14, 2024, at 12:15 PM, Todd Geist ***@***.***> wrote:﻿
hmmm not so sure...
If you post "application/x-www-form-urlencoded" data an ampersand must be encoded since ampersands are the value separator.

application/x-www-form-urlencoded: the keys and values are encoded in key-value tuples separated by an ampersand (&), with an equals symbol (=) between the key and the value (e.g., first-name=Frida&last-name=Kahlo). Non-alphanumeric characters in both keys and values are percent-encoded: this is the reason why this type is not suitable to use with binary data and you should use multipart/form-data for this purpose instead.

Percent Encoding is also known as Url Encoding.
For reference
https://en.wikipedia.org/wiki/Percent-encoding

**Comment by davegraham92120** [comment]
Confirmed: it was the percent symbol that was causing issues for me.

**Comment by davegraham92120** [comment]
This shows completed but I don't see the fix in the latest.

**Comment by toddgeist** [comment]
what is there to fix?

The data type 'application/x-www-form-urlencoded' calls for each part to be url encoded which is what we are doing. 

> application/x-www-form-urlencoded: the keys and values are encoded in key-value tuples separated by an ampersand (&), with an equals symbol (=) between the key and the value (e.g., first-name=Frida&last-name=Kahlo). Non-alphanumeric characters in both keys and values are percent-encoded: this is the reason why this type is not suitable to use with binary data and you should use multipart/form-data for this purpose instead.

**Comment by davegraham92120** [comment]
@toddgeist You're right of course... if the spec calls for it to be encoded then it should be. Unfortunately there are applications that break when the values are encoded. I found other examples beyond my own. When it breaks there is no way around it other than to turn off encoding. The app developer in my case (Lowe's) has said they aren't going to make changes to their API as they work on a completely new back-end, so I have to adjust. Rather than forking the HTTP repo for this edge case, maybe this proposed change will be acceptable:
![image](https://github.com/user-attachments/assets/76b2bab1-8905-4866-b4c7-4cc1d649f662)
![image](https://github.com/user-attachments/assets/8e016977-fe3a-4088-84a8-4b922107141b)
![image](https://github.com/user-attachments/assets/b0256bc3-c195-4828-b466-eb52bd044540)
Here's the new file for consideration:
[mfm-HTTP-3.fmp12.zip](https://github.com/user-attachments/files/17400170/mfm-HTTP-3.fmp12.zip)

**Comment by toddgeist** [comment]
I dunno. It is edge case.  But that said, we have few edge cases already in there

Does Lowes allow you to use `application/json` instead of application/x-www-form-urlencoded ?

**Comment by davegraham92120** [comment]
They use application/json for everything except the token refresh, which requires x-www-form-urlencoded. 😔
